package com.astral.typer.models

enum class TextEffectType {
    NONE,
    CHROMATIC_ABERRATION,
    GLITCH,
    GLITCH2,
    PIXELATION,
    NEON,
    LONG_SHADOW,
    GAUSSIAN_BLUR,
    HALFTONE,
    MOTION_BLUR,
    FIERY,
    WAVY,
    PARTICLE_DISSOLVE,
    MULTI_GRADIENT,
    RADIAL_BLUR,
    TEXT_DECAY,
    TWIST,
    BULGE_PINCH,
    REFLECTION,
    ZOOM_BLUR,
    SPEED_LINE,
    WOOD_SCRATCH,
    TEXT_TAIL,
    DROP_SHADOW
}
